# Generated by Django 5.2.12 on 2026-03-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currencyprovider',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currencyprovider',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='currencyexchangerate',
            constraint=models.UniqueConstraint(fields=('source_currency', 'exchanged_currency', 'valuation_date'), name='unique_currency_exchange_rate'),
        ),
    ]
